// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dao

import (
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

type Price struct {
	ID        int64           `json:"id"`
	SymbolID  int64           `json:"symbol_id"`
	Price     decimal.Decimal `json:"price"`
	Currency  string          `json:"currency"`
	Timestamp time.Time       `json:"timestamp"`
}

type ScrapingSource struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	BaseUrl        string         `json:"base_url"`
	AdditionalInfo sql.NullString `json:"additional_info"`
}

type Symbol struct {
	ID     int64          `json:"id"`
	Symbol string         `json:"symbol"`
	Name   sql.NullString `json:"name"`
}

type SymbolSource struct {
	ID          int64          `json:"id"`
	SymbolID    int64          `json:"symbol_id"`
	SourceID    int64          `json:"source_id"`
	ScrapeUrl   sql.NullString `json:"scrape_url"`
	Active      sql.NullBool   `json:"active"`
	LastScraped sql.NullTime   `json:"last_scraped"`
}
