// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dao

import (
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

type Cache struct {
	K         string      `json:"k"`
	V         string      `json:"v"`
	ExpiresAt interface{} `json:"expires_at"`
}

type Price struct {
	ID        int64           `json:"id"`
	SymbolID  int64           `json:"symbol_id"`
	Price     decimal.Decimal `json:"price"`
	Currency  string          `json:"currency"`
	Timestamp time.Time       `json:"timestamp"`
}

type ScrapingSource struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	BaseUrl        string         `json:"base_url"`
	AdditionalInfo sql.NullString `json:"additional_info"`
}

type Symbol struct {
	ID     int64          `json:"id"`
	Symbol string         `json:"symbol"`
	Name   sql.NullString `json:"name"`
}

type SymbolSource struct {
	ID          int64        `json:"id"`
	SymbolID    int64        `json:"symbol_id"`
	SourceID    string       `json:"source_id"`
	ScrapeUrl   string       `json:"scrape_url"`
	Active      sql.NullBool `json:"active"`
	LastScraped sql.NullTime `json:"last_scraped"`
}
